export const HOME_ROUTE = "/"
export const LOGIN_ROUTE = "/login"
export const REGISTER_ROUTE = "/register"
export const DIARY_ROUTE = "/diary"
export const EDITOR_ROUTE = "/editor"
export const PROFILE_ROUTE = "/profile"
export const EDITOR_ROUTE_ID = "/editor/:id"